---
- name: Generate admin credentials
  import_tasks: generate_credentials.yml

- name: Install MySQL server
  import_tasks: install.yml

- name: Configure MySQL
  import_tasks: configure.yml

- name: Configure replication for cluster
  import_tasks: replicate.yml
  when: deployment_mode == "cluster"
