---
deployment_mode: "single"       # "single" or "cluster"
mongodb_credentials_path: "/tmp/mongodb_credentials.txt"

mongodb_version: "7.0.14"
mongodb_repo_codename: "jammy"
mongodb_repo_line: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu {{ mongodb_repo_codename }}/mongodb-org/7.0 multiverse"
mongodb_key_url: "https://www.mongodb.org/static/pgp/server-7.0.asc"
mongodb_keyring_path: "/usr/share/keyrings/mongodb-server-7.0.gpg"

replset_name: "sb-mongo-repl"
keyfile_path: "/var/lib/mongodb/encryption"
keyfile_owner: "mongodb"
keyfile_group: "mongodb"
keyfile_mode: "0600"

mongod_bind_ip: "0.0.0.0"
mongod_port: 27017

mongodb_packages:
  - "mongodb-org={{ mongodb_version }}"
  - "mongodb-org-database={{ mongodb_version }}"
  - "mongodb-org-server={{ mongodb_version }}"
  - "mongodb-org-mongos={{ mongodb_version }}"
  - "mongodb-org-tools={{ mongodb_version }}"
